Repository GoogleCloudPlatform/gke-istio-vpn-demo, pull requests merged in 2019-03, with the labels that each got.

#23 Move istio installation to terraform and fix the delete logic
  scripts/create.sh
  scripts/teardown.sh
  terraform/main.tf
  terraform/provider.tf
Labels: approved, cla: yes, gke-helmsman, lgtm, size/M

#24 Updating document to use make validate
  README.md
Labels: approved, bug, cla: yes, gke-helmsman, size/XS

#25 Adding README-QWIKLABS file
  README-QWIKLABS.md
Labels: approved, cla: yes, gke-helmsman, lgtm

#26 Updated the CloudShell button and QWIKLAB README
  README-QWIKLABS.md
  README.md
Labels: approved, cla: yes, gke-helmsman, lgtm, size/M

#28 Use latest version for gke
  scripts/istio.env
  scripts/teardown.sh
Labels: approved, cla: yes, gke-helmsman, size/XS

#29 add wait for firewall rules deletion
  scripts/teardown.sh
Labels: cla: yes, gke-helmsman, size/S
