Repository GoogleCloudPlatform/gke-istio-vpn-demo, pull requests merged in 2019-07, with the labels that each got.

#32 Update Istio Version
  scripts/create.sh
  scripts/istio.env
  scripts/teardown.sh
Labels: cla: yes, gke-helmsman, size/M

#19 WIP Readme updates
  README.md
Labels: approved, cla: yes, gke-helmsman, size/M, wip

#27 Cloudshell link updated and instructions to add sub module
  README-QWIKLABS.md
  README.md
  scripts/teardown.sh
Labels: cla: yes, gke-helmsman, size/S

#15 updated boilerplate files and Makefile
  Makefile
  test/boilerplate/boilerplate.BUILD.txt
  test/boilerplate/boilerplate.WORKSPACE.txt
  test/boilerplate/boilerplate.bazel.txt
  test/boilerplate/boilerplate.bzl.txt
  test/boilerplate/boilerplate.css.txt
  test/boilerplate/boilerplate.go.preamble
  test/boilerplate/boilerplate.html.preamble
  test/boilerplate/boilerplate.html.txt
  test/boilerplate/boilerplate.java.txt
  test/boilerplate/boilerplate.js.txt
  test/boilerplate/boilerplate.py.preamble
  test/boilerplate/boilerplate.scss.txt
  test/boilerplate/boilerplate.sh.preamble
  test/boilerplate/boilerplate.ts.txt
  test/boilerplate/boilerplate.xml.preamble
  test/make.sh
  test/verify_boilerplate.py
Labels: approved, cla: yes, gke-helmsman, size/L
